// My adapted interface
export interface Service extends Omit<PayloadService, 'featuredImage'> {
	featuredImage: PayloadMedia & { url: string }
}

// Generated by Payload
export interface PayloadMedia {
	id: number
	alt: string
	updatedAt: string
	createdAt: string
	url?: string | null
	thumbnailURL?: string | null
	filename?: string | null
	mimeType?: string | null
	filesize?: number | null
	width?: number | null
	height?: number | null
	focalX?: number | null
	focalY?: number | null
}

// Generated by Payload
export interface PayloadService {
	id: number
	serviceType: string
	slug: string
	tagline: string
	metaDescription: string
	featuredImage: number | PayloadMedia
	content: {
		root: {
			type: string
			children: {
				type: string
				version: number
				[k: string]: unknown
			}[]
			direction: ('ltr' | 'rtl') | null
			format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
			indent: number
			version: number
		}
		[k: string]: unknown
	}
	updatedAt: string
	createdAt: string
}